name: NPM Test

on:
  push:
    branches:
      - main

jobs:
  npm_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to my-react-app directory
        run: cd /my-react-app

      - name: Install dependencies
        run: npm install

      - name: Run Jest test
        run: npm test
