name: Build and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install
      working-directory: my-react-app

    - name: Build Project
      run: npm run build
      working-directory: my-react-app

    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-react-app-build
        path: my-react-app/dist
